FORMAT: 1A
HOST: http://api.honbot.com/

# honbot

This backend powers the website honbot.com. It's pretty cool.

## Group Player

Get a player.

## Player [/player/{nickname}]

A Player object has the following attributes:

+ there's a lot of attributes. Trust me.

+ Parameters
    + nickname (required, string, `stridex`) ... Nickname/Username of the Player in form of an string

### View a Player Detail [GET]

+ Response 200 (application/json)

                {
                  "acc_actions": 7684, 
                  "acc_annihilation": 0, 
                  "acc_avg_apm": 147.4383, 
                  "acc_avg_assists": 1.3333, 
                  "acc_avg_consumables": 1.0, 
                  "acc_avg_creeps": 39.3333, 
                  "acc_avg_deaths": 1.6667, 
                  "acc_avg_denies": 8.3333, 
                  "acc_avg_gpm": 179.9039, 
                  "acc_avg_kills": 5.0, 
                  "acc_avg_time": 17.3722, 
                  "acc_avg_wards": 0.3333, 
                  "acc_avg_xpm": 321.893, 
                  "acc_bdmg": 0, 
                  "acc_bdmgexp": 0, 
                  "acc_bgold": 0, 
                  "acc_bloodlust": 1, 
                  "acc_buybacks": 0, 
                  "acc_concedes": 3, 
                  "acc_concedevotes": 1, 
                  "acc_consumables": 3, 
                  "acc_deaths": 5, 
                  "acc_denies": 25, 
                  "acc_discos": 1, 
                  "acc_doublekill": 1, 
                  "acc_exp": 16776, 
                  "acc_exp_denied": 969, 
                  "acc_games_played": 3, 
                  "acc_gold": 9376, 
                  "acc_gold_spent": 12720, 
                  "acc_goldlost2death": 1707, 
                  "acc_heroassists": 4, 
                  "acc_herodmg": 15727, 
                  "acc_heroexp": 7232, 
                  "acc_herokills": 15, 
                  "acc_herokillsgold": 5122, 
                  "acc_humiliation": 0, 
                  "acc_kadr": 4, 
                  "acc_kdr": 3.0, 
                  "acc_kicked": 0, 
                  "acc_ks10": 0, 
                  "acc_ks15": 0, 
                  "acc_ks3": 2, 
                  "acc_ks4": 1, 
                  "acc_ks5": 1, 
                  "acc_ks6": 0, 
                  "acc_ks7": 0, 
                  "acc_ks8": 0, 
                  "acc_ks9": 0, 
                  "acc_losses": 3, 
                  "acc_mmr": 1465.206, 
                  "acc_nemesis": 0, 
                  "acc_neutralcreepdmg": 6362, 
                  "acc_neutralcreepgold": 301, 
                  "acc_neutralcreepkills": 11, 
                  "acc_quadkill": 0, 
                  "acc_razed": 0, 
                  "acc_retribution": 0, 
                  "acc_secs": 3127, 
                  "acc_secs_dead": 180, 
                  "acc_smackdown": 2, 
                  "acc_teamcreepdmg": 26698, 
                  "acc_teamcreepexp": 8825, 
                  "acc_teamcreepgold": 3513, 
                  "acc_teamcreepkills": 107, 
                  "acc_time_earning_exp": 3127, 
                  "acc_triplekill": 0, 
                  "acc_tsr": 4.53973630184934, 
                  "acc_wards": 1, 
                  "acc_winpercent": 0.0, 
                  "acc_wins": 0, 
                  "avatar": "https://s3.amazonaws.com/naeu-icb2/icons/3/258/3258111/1.cai", 
                  "avatar_updated": "2015-02-01T18:35:17.198590+00:00", 
                  "cs_actions": 1185521, 
                  "cs_annihilation": 0, 
                  "cs_avg_apm": 135.246, 
                  "cs_avg_assists": 9.4906, 
                  "cs_avg_consumables": 4.5, 
                  "cs_avg_creeps": 68.0692, 
                  "cs_avg_deaths": 5.0283, 
                  "cs_avg_denies": 7.9434, 
                  "cs_avg_gpm": 428.418, 
                  "cs_avg_kills": 6.2075, 
                  "cs_avg_time": 27.565, 
                  "cs_avg_wards": 0.8711, 
                  "cs_avg_xpm": 502.0345, 
                  "cs_bdmg": 380018, 
                  "cs_bdmgexp": 262100, 
                  "cs_bgold": 529669, 
                  "cs_bloodlust": 33, 
                  "cs_buybacks": 14, 
                  "cs_concedes": 124, 
                  "cs_concedevotes": 142, 
                  "cs_consumables": 1431, 
                  "cs_deaths": 1599, 
                  "cs_denies": 2526, 
                  "cs_discos": 10, 
                  "cs_doublekill": 268, 
                  "cs_exp": 4400667, 
                  "cs_exp_denied": 53056, 
                  "cs_games_played": 318, 
                  "cs_gold": 3755369, 
                  "cs_gold_spent": 3560995, 
                  "cs_goldlost2death": 0, 
                  "cs_heroassists": 3018, 
                  "cs_herodmg": 3970910, 
                  "cs_heroexp": 2438495, 
                  "cs_herokills": 1974, 
                  "cs_herokillsgold": 1789515, 
                  "cs_humiliation": 3, 
                  "cs_kadr": 3, 
                  "cs_kdr": 1.2345, 
                  "cs_kicked": 1, 
                  "cs_ks10": 9, 
                  "cs_ks15": 2, 
                  "cs_ks3": 162, 
                  "cs_ks4": 105, 
                  "cs_ks5": 74, 
                  "cs_ks6": 48, 
                  "cs_ks7": 33, 
                  "cs_ks8": 25, 
                  "cs_ks9": 12, 
                  "cs_level": 14, 
                  "cs_level_exp": 11710, 
                  "cs_losses": 153, 
                  "cs_mmr": 1578.653, 
                  "cs_nemesis": 2538, 
                  "cs_neutralcreepdmg": 2275283, 
                  "cs_neutralcreepgold": 137215, 
                  "cs_neutralcreepkills": 3080, 
                  "cs_quadkill": 8, 
                  "cs_razed": 330, 
                  "cs_retribution": 20, 
                  "cs_secs": 525940, 
                  "cs_secs_dead": 278254, 
                  "cs_smackdown": 51, 
                  "cs_teamcreepdmg": 7010091, 
                  "cs_teamcreepexp": 1473882, 
                  "cs_teamcreepgold": 697116, 
                  "cs_teamcreepkills": 18566, 
                  "cs_time_earning_exp": 522311, 
                  "cs_triplekill": 50, 
                  "cs_tsr": 5.49470651185373, 
                  "cs_wards": 277, 
                  "cs_winpercent": 0.5189, 
                  "cs_wins": 165, 
                  "id": 3258111, 
                  "nickname": "stridex", 
                  "rnk_actions": 5119229, 
                  "rnk_annihilation": 0, 
                  "rnk_avg_apm": 121.8201, 
                  "rnk_avg_assists": 7.7596, 
                  "rnk_avg_consumables": 4.2168, 
                  "rnk_avg_creeps": 81.1711, 
                  "rnk_avg_deaths": 4.6626, 
                  "rnk_avg_denies": 9.8517, 
                  "rnk_avg_gpm": 224.7434, 
                  "rnk_avg_kills": 4.1483, 
                  "rnk_avg_time": 34.2485, 
                  "rnk_avg_wards": 1.9527, 
                  "rnk_avg_xpm": 356.5421, 
                  "rnk_bdmg": 941055, 
                  "rnk_bgold": 1484922, 
                  "rnk_bloodlust": 87, 
                  "rnk_buybacks": 20, 
                  "rnk_concedes": 523, 
                  "rnk_concedevotes": 531, 
                  "rnk_consumables": 5174, 
                  "rnk_deaths": 5721, 
                  "rnk_denies": 12088, 
                  "rnk_discos": 10, 
                  "rnk_doublekill": 532, 
                  "rnk_exp": 14982915, 
                  "rnk_exp_denied": 545129, 
                  "rnk_games_played": 1227, 
                  "rnk_gold": 9444357, 
                  "rnk_gold_spent": 9476973, 
                  "rnk_goldlost2death": 1567665, 
                  "rnk_heroassists": 9521, 
                  "rnk_herodmg": 11790951, 
                  "rnk_heroexp": 6331200, 
                  "rnk_herokills": 5090, 
                  "rnk_herokillsgold": 2895222, 
                  "rnk_humiliation": 5, 
                  "rnk_kadr": 3, 
                  "rnk_kdr": 0.8897, 
                  "rnk_kicked": 1, 
                  "rnk_ks10": 6, 
                  "rnk_ks15": 1, 
                  "rnk_ks3": 463, 
                  "rnk_ks4": 268, 
                  "rnk_ks5": 155, 
                  "rnk_ks6": 94, 
                  "rnk_ks7": 54, 
                  "rnk_ks8": 25, 
                  "rnk_ks9": 14, 
                  "rnk_level": 29, 
                  "rnk_level_exp": 43865, 
                  "rnk_losses": 596, 
                  "rnk_mmr": 1706.567, 
                  "rnk_nemesis": 8030, 
                  "rnk_neutralcreepdmg": 15720911, 
                  "rnk_neutralcreepgold": 965694, 
                  "rnk_neutralcreepkills": 23707, 
                  "rnk_quadkill": 2, 
                  "rnk_razed": 803, 
                  "rnk_retribution": 82, 
                  "rnk_secs": 2521371, 
                  "rnk_secs_dead": 917298, 
                  "rnk_smackdown": 54, 
                  "rnk_teamcreepdmg": 29149265, 
                  "rnk_teamcreepexp": 6972004, 
                  "rnk_teamcreepgold": 2771059, 
                  "rnk_teamcreepkills": 75890, 
                  "rnk_time_earning_exp": 2514945, 
                  "rnk_triplekill": 57, 
                  "rnk_tsr": 4.78680048352567, 
                  "rnk_wards": 2396, 
                  "rnk_winpercent": 0.5143, 
                  "rnk_wins": 631, 
                  "updated": "2015-04-01T06:07:12.230047+00:00"
                }
