# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.PositiveIntegerField(serialize=False, primary_key=True, unique=True)),
                ('mode', models.CharField(db_index=True, max_length=3)),
                ('date', models.DateTimeField(null=True)),
                ('length', models.PositiveIntegerField(null=True, default=0)),
                ('map_used', models.CharField(null=True, max_length=18, default='')),
                ('major', models.PositiveSmallIntegerField(null=True, default=0)),
                ('minor', models.PositiveSmallIntegerField(null=True, default=0)),
                ('revision', models.PositiveSmallIntegerField(null=True, default=0)),
                ('build', models.PositiveSmallIntegerField(null=True, default=0)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-match_id'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.PositiveIntegerField(db_index=True, serialize=False, primary_key=True, unique=True)),
                ('nickname', models.CharField(db_index=True, null=True, max_length=16)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added', models.DateTimeField(null=True, auto_now_add=True)),
                ('avatar', models.URLField(default='', max_length=100)),
                ('avatar_updated', models.DateTimeField(null=True)),
                ('rnk_history', models.TextField(default='')),
                ('cs_history', models.TextField(default='')),
                ('acc_history', models.TextField(default='')),
                ('history_updated', models.DateTimeField(null=True, blank=True)),
                ('rnk_games_played', models.PositiveIntegerField(null=True)),
                ('rnk_wins', models.PositiveIntegerField(null=True)),
                ('rnk_losses', models.PositiveIntegerField(null=True)),
                ('rnk_concedes', models.PositiveIntegerField(null=True)),
                ('rnk_concedevotes', models.PositiveIntegerField(null=True)),
                ('rnk_buybacks', models.PositiveIntegerField(null=True)),
                ('rnk_discos', models.PositiveIntegerField(null=True)),
                ('rnk_kicked', models.PositiveIntegerField(null=True)),
                ('rnk_mmr', models.FloatField(null=True)),
                ('rnk_herokills', models.PositiveIntegerField(null=True)),
                ('rnk_herodmg', models.PositiveIntegerField(null=True)),
                ('rnk_heroexp', models.PositiveIntegerField(null=True)),
                ('rnk_herokillsgold', models.PositiveIntegerField(null=True)),
                ('rnk_heroassists', models.PositiveIntegerField(null=True)),
                ('rnk_deaths', models.PositiveIntegerField(null=True)),
                ('rnk_goldlost2death', models.PositiveIntegerField(null=True)),
                ('rnk_secs_dead', models.PositiveIntegerField(null=True)),
                ('rnk_teamcreepkills', models.PositiveIntegerField(null=True)),
                ('rnk_teamcreepdmg', models.PositiveIntegerField(null=True)),
                ('rnk_teamcreepexp', models.PositiveIntegerField(null=True)),
                ('rnk_teamcreepgold', models.PositiveIntegerField(null=True)),
                ('rnk_neutralcreepkills', models.PositiveIntegerField(null=True)),
                ('rnk_neutralcreepdmg', models.PositiveIntegerField(null=True)),
                ('rnk_neutralcreepexp', models.PositiveIntegerField(null=True)),
                ('rnk_neutralcreepgold', models.PositiveIntegerField(null=True)),
                ('rnk_bdmg', models.PositiveIntegerField(null=True)),
                ('rnk_razed', models.PositiveIntegerField(null=True)),
                ('rnk_bgold', models.PositiveIntegerField(null=True)),
                ('rnk_denies', models.PositiveIntegerField(null=True)),
                ('rnk_exp_denied', models.PositiveIntegerField(null=True)),
                ('rnk_gold', models.PositiveIntegerField(null=True)),
                ('rnk_gold_spent', models.PositiveIntegerField(null=True)),
                ('rnk_exp', models.PositiveIntegerField(null=True)),
                ('rnk_actions', models.PositiveIntegerField(null=True)),
                ('rnk_secs', models.PositiveIntegerField(null=True)),
                ('rnk_consumables', models.PositiveIntegerField(null=True)),
                ('rnk_wards', models.PositiveIntegerField(null=True)),
                ('rnk_level', models.PositiveIntegerField(null=True)),
                ('rnk_level_exp', models.PositiveIntegerField(null=True)),
                ('rnk_min_exp', models.PositiveIntegerField(null=True)),
                ('rnk_max_exp', models.PositiveIntegerField(null=True)),
                ('rnk_time_earning_exp', models.PositiveIntegerField(null=True)),
                ('rnk_bloodlust', models.PositiveIntegerField(null=True)),
                ('rnk_doublekill', models.PositiveIntegerField(null=True)),
                ('rnk_triplekill', models.PositiveIntegerField(null=True)),
                ('rnk_quadkill', models.PositiveIntegerField(null=True)),
                ('rnk_annihilation', models.PositiveIntegerField(null=True)),
                ('rnk_ks3', models.PositiveIntegerField(null=True)),
                ('rnk_ks4', models.PositiveIntegerField(null=True)),
                ('rnk_ks5', models.PositiveIntegerField(null=True)),
                ('rnk_ks6', models.PositiveIntegerField(null=True)),
                ('rnk_ks7', models.PositiveIntegerField(null=True)),
                ('rnk_ks8', models.PositiveIntegerField(null=True)),
                ('rnk_ks9', models.PositiveIntegerField(null=True)),
                ('rnk_ks10', models.PositiveIntegerField(null=True)),
                ('rnk_ks15', models.PositiveIntegerField(null=True)),
                ('rnk_smackdown', models.PositiveIntegerField(null=True)),
                ('rnk_humiliation', models.PositiveIntegerField(null=True)),
                ('rnk_nemesis', models.PositiveIntegerField(null=True)),
                ('rnk_retribution', models.PositiveIntegerField(null=True)),
                ('rnk_avg_kills', models.FloatField(null=True)),
                ('rnk_avg_deaths', models.FloatField(null=True)),
                ('rnk_avg_assists', models.FloatField(null=True)),
                ('rnk_avg_creeps', models.FloatField(null=True)),
                ('rnk_avg_denies', models.FloatField(null=True)),
                ('rnk_avg_xpm', models.FloatField(null=True)),
                ('rnk_avg_apm', models.FloatField(null=True)),
                ('rnk_avg_gpm', models.FloatField(null=True)),
                ('rnk_avg_wards', models.FloatField(null=True)),
                ('rnk_avg_consumables', models.FloatField(null=True)),
                ('rnk_avg_time', models.FloatField(null=True)),
                ('rnk_kdr', models.FloatField(null=True)),
                ('rnk_kadr', models.FloatField(null=True)),
                ('rnk_winpercent', models.FloatField(null=True)),
                ('rnk_tsr', models.FloatField(null=True)),
                ('cs_games_played', models.PositiveIntegerField(null=True)),
                ('cs_wins', models.PositiveIntegerField(null=True)),
                ('cs_losses', models.PositiveIntegerField(null=True)),
                ('cs_concedes', models.PositiveIntegerField(null=True)),
                ('cs_concedevotes', models.PositiveIntegerField(null=True)),
                ('cs_buybacks', models.PositiveIntegerField(null=True)),
                ('cs_discos', models.PositiveIntegerField(null=True)),
                ('cs_kicked', models.PositiveIntegerField(null=True)),
                ('cs_mmr', models.FloatField(null=True)),
                ('cs_herokills', models.PositiveIntegerField(null=True)),
                ('cs_herodmg', models.PositiveIntegerField(null=True)),
                ('cs_heroexp', models.PositiveIntegerField(null=True)),
                ('cs_herokillsgold', models.PositiveIntegerField(null=True)),
                ('cs_heroassists', models.PositiveIntegerField(null=True)),
                ('cs_deaths', models.PositiveIntegerField(null=True)),
                ('cs_secs_dead', models.PositiveIntegerField(null=True)),
                ('cs_teamcreepkills', models.PositiveIntegerField(null=True)),
                ('cs_teamcreepdmg', models.PositiveIntegerField(null=True)),
                ('cs_teamcreepexp', models.PositiveIntegerField(null=True)),
                ('cs_teamcreepgold', models.PositiveIntegerField(null=True)),
                ('cs_neutralcreepkills', models.PositiveIntegerField(null=True)),
                ('cs_neutralcreepdmg', models.PositiveIntegerField(null=True)),
                ('cs_neutralcreepexp', models.PositiveIntegerField(null=True)),
                ('cs_neutralcreepgold', models.PositiveIntegerField(null=True)),
                ('cs_bdmg', models.PositiveIntegerField(null=True)),
                ('cs_bdmgexp', models.PositiveIntegerField(null=True)),
                ('cs_razed', models.PositiveIntegerField(null=True)),
                ('cs_bgold', models.PositiveIntegerField(null=True)),
                ('cs_denies', models.PositiveIntegerField(null=True)),
                ('cs_exp_denied', models.PositiveIntegerField(null=True)),
                ('cs_gold', models.PositiveIntegerField(null=True)),
                ('cs_gold_spent', models.PositiveIntegerField(null=True)),
                ('cs_exp', models.PositiveIntegerField(null=True)),
                ('cs_actions', models.PositiveIntegerField(null=True)),
                ('cs_secs', models.PositiveIntegerField(null=True)),
                ('cs_consumables', models.PositiveIntegerField(null=True)),
                ('cs_wards', models.PositiveIntegerField(null=True)),
                ('cs_level', models.PositiveIntegerField(null=True)),
                ('cs_level_exp', models.PositiveIntegerField(null=True)),
                ('cs_min_exp', models.PositiveIntegerField(null=True)),
                ('cs_max_exp', models.PositiveIntegerField(null=True)),
                ('cs_time_earning_exp', models.PositiveIntegerField(null=True)),
                ('cs_bloodlust', models.PositiveIntegerField(null=True)),
                ('cs_doublekill', models.PositiveIntegerField(null=True)),
                ('cs_triplekill', models.PositiveIntegerField(null=True)),
                ('cs_quadkill', models.PositiveIntegerField(null=True)),
                ('cs_annihilation', models.PositiveIntegerField(null=True)),
                ('cs_ks4', models.PositiveIntegerField(null=True)),
                ('cs_ks5', models.PositiveIntegerField(null=True)),
                ('cs_ks6', models.PositiveIntegerField(null=True)),
                ('cs_ks3', models.PositiveIntegerField(null=True)),
                ('cs_ks7', models.PositiveIntegerField(null=True)),
                ('cs_ks8', models.PositiveIntegerField(null=True)),
                ('cs_ks9', models.PositiveIntegerField(null=True)),
                ('cs_ks10', models.PositiveIntegerField(null=True)),
                ('cs_ks15', models.PositiveIntegerField(null=True)),
                ('cs_smackdown', models.PositiveIntegerField(null=True)),
                ('cs_humiliation', models.PositiveIntegerField(null=True)),
                ('cs_nemesis', models.PositiveIntegerField(null=True)),
                ('cs_retribution', models.PositiveIntegerField(null=True)),
                ('cs_avg_kills', models.FloatField(null=True)),
                ('cs_avg_deaths', models.FloatField(null=True)),
                ('cs_avg_assists', models.FloatField(null=True)),
                ('cs_avg_creeps', models.FloatField(null=True)),
                ('cs_avg_denies', models.FloatField(null=True)),
                ('cs_avg_xpm', models.FloatField(null=True)),
                ('cs_avg_apm', models.FloatField(null=True)),
                ('cs_avg_gpm', models.FloatField(null=True)),
                ('cs_avg_consumables', models.FloatField(null=True)),
                ('cs_avg_time', models.FloatField(null=True)),
                ('cs_avg_wards', models.FloatField(null=True)),
                ('cs_kdr', models.FloatField(null=True)),
                ('cs_kadr', models.FloatField(null=True)),
                ('cs_winpercent', models.FloatField(null=True)),
                ('cs_tsr', models.FloatField(null=True)),
                ('acc_games_played', models.PositiveIntegerField(null=True)),
                ('acc_wins', models.PositiveIntegerField(null=True)),
                ('acc_losses', models.PositiveIntegerField(null=True)),
                ('acc_concedes', models.PositiveIntegerField(null=True)),
                ('acc_concedevotes', models.PositiveIntegerField(null=True)),
                ('acc_buybacks', models.PositiveIntegerField(null=True)),
                ('acc_discos', models.PositiveIntegerField(null=True)),
                ('acc_kicked', models.PositiveIntegerField(null=True)),
                ('acc_mmr', models.FloatField(null=True)),
                ('acc_herokills', models.PositiveIntegerField(null=True)),
                ('acc_herodmg', models.PositiveIntegerField(null=True)),
                ('acc_heroexp', models.PositiveIntegerField(null=True)),
                ('acc_herokillsgold', models.PositiveIntegerField(null=True)),
                ('acc_heroassists', models.PositiveIntegerField(null=True)),
                ('acc_deaths', models.PositiveIntegerField(null=True)),
                ('acc_goldlost2death', models.PositiveIntegerField(null=True)),
                ('acc_secs_dead', models.PositiveIntegerField(null=True)),
                ('acc_teamcreepkills', models.PositiveIntegerField(null=True)),
                ('acc_teamcreepdmg', models.PositiveIntegerField(null=True)),
                ('acc_teamcreepexp', models.PositiveIntegerField(null=True)),
                ('acc_teamcreepgold', models.PositiveIntegerField(null=True)),
                ('acc_neutralcreepkills', models.PositiveIntegerField(null=True)),
                ('acc_neutralcreepdmg', models.PositiveIntegerField(null=True)),
                ('acc_neutralcreepexp', models.PositiveIntegerField(null=True)),
                ('acc_neutralcreepgold', models.PositiveIntegerField(null=True)),
                ('acc_bdmg', models.PositiveIntegerField(null=True)),
                ('acc_bdmgexp', models.PositiveIntegerField(null=True)),
                ('acc_razed', models.PositiveIntegerField(null=True)),
                ('acc_bgold', models.PositiveIntegerField(null=True)),
                ('acc_denies', models.PositiveIntegerField(null=True)),
                ('acc_exp_denied', models.PositiveIntegerField(null=True)),
                ('acc_gold', models.PositiveIntegerField(null=True)),
                ('acc_gold_spent', models.PositiveIntegerField(null=True)),
                ('acc_exp', models.PositiveIntegerField(null=True)),
                ('acc_actions', models.PositiveIntegerField(null=True)),
                ('acc_secs', models.PositiveIntegerField(null=True)),
                ('acc_consumables', models.PositiveIntegerField(null=True)),
                ('acc_wards', models.PositiveIntegerField(null=True)),
                ('acc_time_earning_exp', models.PositiveIntegerField(null=True)),
                ('acc_bloodlust', models.PositiveIntegerField(null=True)),
                ('acc_doublekill', models.PositiveIntegerField(null=True)),
                ('acc_triplekill', models.PositiveIntegerField(null=True)),
                ('acc_quadkill', models.PositiveIntegerField(null=True)),
                ('acc_annihilation', models.PositiveIntegerField(null=True)),
                ('acc_ks3', models.PositiveIntegerField(null=True)),
                ('acc_ks4', models.PositiveIntegerField(null=True)),
                ('acc_ks5', models.PositiveIntegerField(null=True)),
                ('acc_ks6', models.PositiveIntegerField(null=True)),
                ('acc_ks7', models.PositiveIntegerField(null=True)),
                ('acc_ks8', models.PositiveIntegerField(null=True)),
                ('acc_ks9', models.PositiveIntegerField(null=True)),
                ('acc_ks10', models.PositiveIntegerField(null=True)),
                ('acc_ks15', models.PositiveIntegerField(null=True)),
                ('acc_smackdown', models.PositiveIntegerField(null=True)),
                ('acc_humiliation', models.PositiveIntegerField(null=True)),
                ('acc_nemesis', models.PositiveIntegerField(null=True)),
                ('acc_retribution', models.PositiveIntegerField(null=True)),
                ('acc_avg_kills', models.FloatField(null=True)),
                ('acc_avg_deaths', models.FloatField(null=True)),
                ('acc_avg_assists', models.FloatField(null=True)),
                ('acc_avg_creeps', models.FloatField(null=True)),
                ('acc_avg_denies', models.FloatField(null=True)),
                ('acc_avg_xpm', models.FloatField(null=True)),
                ('acc_avg_apm', models.FloatField(null=True)),
                ('acc_avg_gpm', models.FloatField(null=True)),
                ('acc_avg_consumables', models.FloatField(null=True)),
                ('acc_avg_time', models.FloatField(null=True)),
                ('acc_avg_wards', models.FloatField(null=True)),
                ('acc_kdr', models.FloatField(null=True)),
                ('acc_kadr', models.FloatField(null=True)),
                ('acc_winpercent', models.FloatField(null=True)),
                ('acc_tsr', models.FloatField(null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PlayerMatchACC',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('player_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('nickname', models.CharField(max_length=16)),
                ('clan_id', models.PositiveSmallIntegerField(null=True, default=0)),
                ('hero_id', models.PositiveSmallIntegerField(null=True, default=0)),
                ('position', models.PositiveSmallIntegerField(null=True, default=0)),
                ('team', models.PositiveSmallIntegerField(null=True, default=0)),
                ('level', models.PositiveSmallIntegerField(null=True, default=0)),
                ('win', models.BooleanField(default=False)),
                ('losses', models.PositiveSmallIntegerField(null=True, default=0)),
                ('concedes', models.PositiveSmallIntegerField(null=True, default=0)),
                ('concedevotes', models.PositiveSmallIntegerField(null=True, default=0)),
                ('buybacks', models.PositiveSmallIntegerField(null=True, default=0)),
                ('discos', models.PositiveSmallIntegerField(null=True, default=0)),
                ('kicked', models.PositiveSmallIntegerField(null=True, default=0)),
                ('mmr_change', models.FloatField(null=True, default=0)),
                ('herodmg', models.PositiveIntegerField(null=True, default=0)),
                ('kills', models.PositiveSmallIntegerField(null=True, default=0)),
                ('assists', models.PositiveSmallIntegerField(null=True, default=0)),
                ('deaths', models.PositiveSmallIntegerField(null=True, default=0)),
                ('kdr', models.FloatField(null=True, default=0)),
                ('goldlost2death', models.PositiveIntegerField(null=True, default=0)),
                ('secs_dead', models.PositiveSmallIntegerField(null=True, default=0)),
                ('cs', models.PositiveSmallIntegerField(null=True, default=0)),
                ('bdmg', models.PositiveIntegerField(null=True, default=0)),
                ('denies', models.PositiveSmallIntegerField(null=True, default=0)),
                ('gpm', models.FloatField(null=True, default=0)),
                ('xpm', models.FloatField(null=True, default=0)),
                ('apm', models.FloatField(null=True, default=0)),
                ('consumables', models.PositiveSmallIntegerField(null=True, default=0)),
                ('wards', models.PositiveSmallIntegerField(null=True, default=0)),
                ('items', models.CharField(default='', max_length=50)),
                ('match', models.ForeignKey(to='hb.Match')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PlayerMatchCS',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('player_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('nickname', models.CharField(max_length=16)),
                ('clan_id', models.PositiveSmallIntegerField(null=True, default=0)),
                ('hero_id', models.PositiveSmallIntegerField(null=True, default=0)),
                ('position', models.PositiveSmallIntegerField(null=True, default=0)),
                ('team', models.PositiveSmallIntegerField(null=True, default=0)),
                ('level', models.PositiveSmallIntegerField(null=True, default=0)),
                ('win', models.BooleanField(default=False)),
                ('losses', models.PositiveSmallIntegerField(null=True, default=0)),
                ('concedes', models.PositiveSmallIntegerField(null=True, default=0)),
                ('concedevotes', models.PositiveSmallIntegerField(null=True, default=0)),
                ('buybacks', models.PositiveSmallIntegerField(null=True, default=0)),
                ('discos', models.PositiveSmallIntegerField(null=True, default=0)),
                ('kicked', models.PositiveSmallIntegerField(null=True, default=0)),
                ('mmr_change', models.FloatField(null=True, default=0)),
                ('herodmg', models.PositiveIntegerField(null=True, default=0)),
                ('kills', models.PositiveSmallIntegerField(null=True, default=0)),
                ('assists', models.PositiveSmallIntegerField(null=True, default=0)),
                ('deaths', models.PositiveSmallIntegerField(null=True, default=0)),
                ('kdr', models.FloatField(null=True, default=0)),
                ('goldlost2death', models.PositiveIntegerField(null=True, default=0)),
                ('secs_dead', models.PositiveSmallIntegerField(null=True, default=0)),
                ('cs', models.PositiveSmallIntegerField(null=True, default=0)),
                ('bdmg', models.PositiveIntegerField(null=True, default=0)),
                ('denies', models.PositiveSmallIntegerField(null=True, default=0)),
                ('gpm', models.FloatField(null=True, default=0)),
                ('xpm', models.FloatField(null=True, default=0)),
                ('apm', models.FloatField(null=True, default=0)),
                ('consumables', models.PositiveSmallIntegerField(null=True, default=0)),
                ('wards', models.PositiveSmallIntegerField(null=True, default=0)),
                ('items', models.CharField(default='', max_length=50)),
                ('match', models.ForeignKey(to='hb.Match')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PlayerMatchRNK',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('player_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('nickname', models.CharField(max_length=16)),
                ('clan_id', models.PositiveSmallIntegerField(null=True, default=0)),
                ('hero_id', models.PositiveSmallIntegerField(null=True, default=0)),
                ('position', models.PositiveSmallIntegerField(null=True, default=0)),
                ('team', models.PositiveSmallIntegerField(null=True, default=0)),
                ('level', models.PositiveSmallIntegerField(null=True, default=0)),
                ('win', models.BooleanField(default=False)),
                ('losses', models.PositiveSmallIntegerField(null=True, default=0)),
                ('concedes', models.PositiveSmallIntegerField(null=True, default=0)),
                ('concedevotes', models.PositiveSmallIntegerField(null=True, default=0)),
                ('buybacks', models.PositiveSmallIntegerField(null=True, default=0)),
                ('discos', models.PositiveSmallIntegerField(null=True, default=0)),
                ('kicked', models.PositiveSmallIntegerField(null=True, default=0)),
                ('mmr_change', models.FloatField(null=True, default=0)),
                ('herodmg', models.PositiveIntegerField(null=True, default=0)),
                ('kills', models.PositiveSmallIntegerField(null=True, default=0)),
                ('assists', models.PositiveSmallIntegerField(null=True, default=0)),
                ('deaths', models.PositiveSmallIntegerField(null=True, default=0)),
                ('kdr', models.FloatField(null=True, default=0)),
                ('goldlost2death', models.PositiveIntegerField(null=True, default=0)),
                ('secs_dead', models.PositiveSmallIntegerField(null=True, default=0)),
                ('cs', models.PositiveSmallIntegerField(null=True, default=0)),
                ('bdmg', models.PositiveIntegerField(null=True, default=0)),
                ('denies', models.PositiveSmallIntegerField(null=True, default=0)),
                ('gpm', models.FloatField(null=True, default=0)),
                ('xpm', models.FloatField(null=True, default=0)),
                ('apm', models.FloatField(null=True, default=0)),
                ('consumables', models.PositiveSmallIntegerField(null=True, default=0)),
                ('wards', models.PositiveSmallIntegerField(null=True, default=0)),
                ('items', models.CharField(default='', max_length=50)),
                ('match', models.ForeignKey(to='hb.Match')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
    ]
