"""empty message

Revision ID: 219e0714a6f
Revises: 42cebf584f8
Create Date: 2014-12-27 22:04:52.608691

"""

# revision identifiers, used by Alembic.
revision = '219e0714a6f'
down_revision = '42cebf584f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playermatch', sa.Column('apm', sa.Float(), nullable=True))
    op.add_column('playermatch', sa.Column('assists', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('bdmg', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('buybacks', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('clan_id', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('concedes', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('concedevotes', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('consumables', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('cs', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('deaths', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('denies', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('exp_denied', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('goldlost2death', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('gpm', sa.Float(), nullable=True))
    op.add_column('playermatch', sa.Column('hero_id', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('herodmg', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('items', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('kdr', sa.Float(), nullable=True))
    op.add_column('playermatch', sa.Column('kills', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('mmr_change', sa.Float(), nullable=True))
    op.add_column('playermatch', sa.Column('nickname', sa.String(length=20), nullable=True))
    op.add_column('playermatch', sa.Column('player_id', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('secs_dead', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('team', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('wards', sa.Integer(), nullable=True))
    op.add_column('playermatch', sa.Column('win', sa.Boolean(), nullable=True))
    op.add_column('playermatch', sa.Column('xpm', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playermatch', 'xpm')
    op.drop_column('playermatch', 'win')
    op.drop_column('playermatch', 'wards')
    op.drop_column('playermatch', 'team')
    op.drop_column('playermatch', 'secs_dead')
    op.drop_column('playermatch', 'position')
    op.drop_column('playermatch', 'player_id')
    op.drop_column('playermatch', 'nickname')
    op.drop_column('playermatch', 'mmr_change')
    op.drop_column('playermatch', 'level')
    op.drop_column('playermatch', 'kills')
    op.drop_column('playermatch', 'kdr')
    op.drop_column('playermatch', 'items')
    op.drop_column('playermatch', 'herodmg')
    op.drop_column('playermatch', 'hero_id')
    op.drop_column('playermatch', 'gpm')
    op.drop_column('playermatch', 'goldlost2death')
    op.drop_column('playermatch', 'exp_denied')
    op.drop_column('playermatch', 'denies')
    op.drop_column('playermatch', 'deaths')
    op.drop_column('playermatch', 'cs')
    op.drop_column('playermatch', 'consumables')
    op.drop_column('playermatch', 'concedevotes')
    op.drop_column('playermatch', 'concedes')
    op.drop_column('playermatch', 'clan_id')
    op.drop_column('playermatch', 'buybacks')
    op.drop_column('playermatch', 'bdmg')
    op.drop_column('playermatch', 'assists')
    op.drop_column('playermatch', 'apm')
    ### end Alembic commands ###
