"""empty message

Revision ID: 21f8f6023f3
Revises: 4b1d6594ec0
Create Date: 2014-12-26 00:36:10.088582

"""

# revision identifiers, used by Alembic.
revision = '21f8f6023f3'
down_revision = '4b1d6594ec0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_player_nickname'), 'player', ['nickname'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_nickname'), table_name='player')
    ### end Alembic commands ###
