"""empty message

Revision ID: 296eb476378
Revises: 3e4d54831e4
Create Date: 2014-12-27 20:49:35.978516

"""

# revision identifiers, used by Alembic.
revision = '296eb476378'
down_revision = '3e4d54831e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
