"""empty message

Revision ID: 3e4d54831e4
Revises: 21f8f6023f3
Create Date: 2014-12-27 00:40:08.268937

"""

# revision identifiers, used by Alembic.
revision = '3e4d54831e4'
down_revision = '21f8f6023f3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('acc_history', postgresql.JSONB(), nullable=True))
    op.add_column('player', sa.Column('cs_history', postgresql.JSONB(), nullable=True))
    op.add_column('player', sa.Column('history_updated', sa.DateTime(), nullable=True))
    op.add_column('player', sa.Column('rnk_history', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'rnk_history')
    op.drop_column('player', 'history_updated')
    op.drop_column('player', 'cs_history')
    op.drop_column('player', 'acc_history')
    ### end Alembic commands ###
