"""empty message

Revision ID: 427722e2d6e
Revises: None
Create Date: 2014-12-20 23:41:08.347753

"""

# revision identifiers, used by Alembic.
revision = '427722e2d6e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
