"""empty message

Revision ID: 42cebf584f8
Revises: 5840c9f8e9f
Create Date: 2014-12-27 21:18:55.134689

"""

# revision identifiers, used by Alembic.
revision = '42cebf584f8'
down_revision = '5840c9f8e9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playermatch', sa.Column('match_id', sa.Integer(), nullable=True))
    op.drop_constraint('playermatch_match_fkey', 'playermatch', type_='foreignkey')
    op.create_foreign_key(None, 'playermatch', 'match', ['match_id'], ['id'])
    op.drop_column('playermatch', 'match')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playermatch', sa.Column('match', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'playermatch', type_='foreignkey')
    op.create_foreign_key('playermatch_match_fkey', 'playermatch', 'match', ['match'], ['id'])
    op.drop_column('playermatch', 'match_id')
    ### end Alembic commands ###
