"""empty message

Revision ID: 4613486f2a1
Revises: 427722e2d6e
Create Date: 2014-12-20 23:46:22.826440

"""

# revision identifiers, used by Alembic.
revision = '4613486f2a1'
down_revision = '427722e2d6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
