"""empty message

Revision ID: 5840c9f8e9f
Revises: 296eb476378
Create Date: 2014-12-27 21:18:00.716425

"""

# revision identifiers, used by Alembic.
revision = '5840c9f8e9f'
down_revision = '296eb476378'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('match', sa.Column('length', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('map_used', sa.String(length=20), nullable=True))
    op.add_column('match', sa.Column('mode', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('version', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_match_map_used'), 'match', ['map_used'], unique=False)
    op.create_index(op.f('ix_match_mode'), 'match', ['mode'], unique=False)
    op.create_index(op.f('ix_match_version'), 'match', ['version'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_version'), table_name='match')
    op.drop_index(op.f('ix_match_mode'), table_name='match')
    op.drop_index(op.f('ix_match_map_used'), table_name='match')
    op.drop_column('match', 'version')
    op.drop_column('match', 'mode')
    op.drop_column('match', 'map_used')
    op.drop_column('match', 'length')
    op.drop_column('match', 'date')
    ### end Alembic commands ###
